server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.html;
        # תמיכה ב-React Router / SPA - ניתוב הכל לקובץ אינדקס
        try_files $uri $uri/ /index.html;
    }
}
