server {
    listen 80;
    server_name momentum.cs.colman.ac.il;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name momentum.cs.colman.ac.il;

    ssl_certificate /etc/ssl/cs/CSB.crt;
    ssl_certificate_key /etc/ssl/cs/myserver.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://frontend;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ {
        proxy_pass http://backend:3000/api/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
